name: Publish NuGet Packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Core dependencies
        run: dotnet restore KarizmaCache/KarizmaCache.csproj

      - name: Build Core project
        run: dotnet build KarizmaCache/KarizmaCache.csproj --configuration Release --no-restore

      - name: Pack Core project
        run: dotnet pack KarizmaCache/KarizmaCache.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish Core package to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.KARIZMACACHE_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.KARIZMACACHE_API_KEY }}
